SRC= tesla_class.c tesla_class_global.c tesla_class_perthread.c \
     tesla_debug.c tesla_key.c tesla_notification.c tesla_store.c \
     tesla_update.c tesla_util.c

OBJ= $(SRC:%.c=libtesla/src/%.o)
CFLAGS= -Iinclude -DHAVE_STRNLEN -Wall

.PHONY: all clean

all: libtesla/libtesla.a libtesla/libtesla.so
	@ :

libtesla/libtesla.a: $(OBJ)
	rm -f $@
	ar rc $@ $^
	ranlib $@

libtesla/libtesla.so: $(OBJ)
	$(CC) -shared -o $@ $^

clean:
	rm -f libtesla/src/*.o libtesla/src/*.a
