#!/bin/sh

if [ "$BUILD_DIR" == "" ]; then BUILD_DIR=build; fi

TESTS="`find ./$BUILD_DIR/libtesla/test -type f | grep -iv cmake`"

TOTAL=0
PASSED=0
FAILED=0

for f in $TESTS; do
	TOTAL=$TOTAL+1
	$f && PASSED=$PASSED+1 || FAILED=$FAILED+1
done

TOTAL=`echo $TOTAL | bc`
PASSED=`echo $PASSED | bc`
FAILED=`echo $FAILED | bc`

if [ `echo "$PASSED + $FAILED" | bc` != $TOTAL ]; then
	echo "Error: $PASSED passes + $FAILED failures != $TOTAL total"
	exit 1
fi

echo "Passed $PASSED/$TOTAL tests"
if [ "$PASSED" != "$TOTAL" ]; then
	exit 1
fi

