#!/bin/sh

CFLAGS="$*"
export CFLAGS
echo "Compiling demo with CFLAGS '$CFLAGS'..."
make clean all || exit 1

echo "Running demo..."

# 'self-signed' is a self-signed certificate: this should pass.
./openssl-api Inputs/self-signed.crt Inputs/self-signed.crt || exit 1

# 'self-signed' has NOT been signed by 'other': this should fail.
./openssl-api Inputs/self-signed.crt Inputs/other.crt || exit 1

# 'hacked' is not even a valid certificate; it should definitely fail!
./openssl-api Inputs/self-signed.crt Inputs/hacked.crt || exit 1

