/*
 * This file is autogenerated by the Tesla CFA compiler
 * via: ../../cfa/splc -t tesla -s ssh_kex ssh_kex.spl
 */

#ifndef SSH_KEX_DEFS_H
#define SSH_KEX_DEFS_H

#include <sys/types.h>

/*
 * Names for events that will trigger SSH_KEX rules
 */
#define SSH_KEX_EVENT_FUNC_PROLOGUE_KEX_FINISH 0
#define SSH_KEX_EVENT_FUNC_PROLOGUE_KEX_CLOSE 1
#define SSH_KEX_EVENT_FUNC_PROLOGUE_KEX_INPUT_KEXINIT 2
#define SSH_KEX_EVENT_FUNC_PROLOGUE_KEX_SETUP 3
#define SSH_KEX_EVENT_FUNC_PROLOGUE_KEX_SEND_KEXINIT 4
#define SSH_KEX_EVENT_FUNC_PROLOGUE_KEX_CHOOSE_CONF 5

/*
 * Prod the SSH_KEX state machine, return (1) if the assertion failed
 */
struct tesla_instance;
void ssh_kex_automata_init(struct tesla_instance *);
int ssh_kex_automata_prod(struct tesla_instance *tip, u_int event);

/*
 * "Public" interfaces to the assertion, to be invoked by load, unload
 * and instrumentation handlers.
 */
#ifndef _KERNEL
void	ssh_kex_init(int scope);
void	ssh_kex_destroy(void);
void    ssh_kex_setaction_debug(void);
#endif
#endif /* SSH_KEX_DEFS_H */
