/*
 * This file is autogenerated by the Tesla CFA compiler
 * via: ../../cfa/splc -t tesla -s ssh ssh.spl
 */


#include <sys/types.h>

#ifdef _KERNEL
#include <sys/systm.h>
#else
#include <assert.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#endif

#include <tesla/tesla_state.h>
#include <tesla/tesla_util.h>

#include "ssh_defs.h"

struct main {
  u_int state : 3;
} __attribute__((__packed__));

#define MAIN_PTR(tip) ((unsigned char *)((tip)->ti_state))
#define MAIN_STATE(tip,off) ((struct main *)(MAIN_PTR(tip)+(off)+1))
#define MAIN_NUM_STATES(tip) (MAIN_PTR(tip)[0])

void
ssh_automata_init(struct tesla_instance *tip) {
  MAIN_NUM_STATES(tip) = 1;
  MAIN_STATE(tip,0)->state = 1; /* 1 */
}

int
ssh_automata_prod(struct tesla_instance *tip, u_int event)
{
  unsigned char newstate[16];
  u_int i, curpos=1;
  struct main tmpstate;
  bzero(newstate, sizeof(newstate));
  switch (event) {
  case 0:  /* EVENT_FUNC_PROLOGUE_PACKET_SEND */
    for (i=0; i < MAIN_NUM_STATES(tip); i++) {
      switch (MAIN_STATE(tip,i)->state) {
      case 4:
        /* event 10 -> 2 */
        tmpstate.state = 2;
        memcpy(&(newstate[curpos]), &tmpstate, 1);
        curpos++;
        /* event 10 -> 5 */
        tmpstate.state = 3;
        memcpy(&(newstate[curpos]), &tmpstate, 1);
        curpos++;
        break;
      default:
        break;
      }
    }
    newstate[0] = curpos-1;
    if (newstate[0] == 0)
      return 1; /* TESLA_ERROR */
    memcpy(MAIN_PTR(tip), &newstate, sizeof(newstate));
    return 0;

  case 1:  /* EVENT_FUNC_PROLOGUE_PACKET_START */
    for (i=0; i < MAIN_NUM_STATES(tip); i++) {
      switch (MAIN_STATE(tip,i)->state) {
      case 3:
        /* event 5 -> 10 */
        tmpstate.state = 4;
        memcpy(&(newstate[curpos]), &tmpstate, 1);
        curpos++;
        break;
      default:
        break;
      }
    }
    newstate[0] = curpos-1;
    if (newstate[0] == 0)
      return 1; /* TESLA_ERROR */
    memcpy(MAIN_PTR(tip), &newstate, sizeof(newstate));
    return 0;

  case 2:  /* EVENT_FUNC_PROLOGUE_PACKET_SET_CONNECTION */
    for (i=0; i < MAIN_NUM_STATES(tip); i++) {
      switch (MAIN_STATE(tip,i)->state) {
      case 1:
        /* event 1 -> 2 */
        tmpstate.state = 2;
        memcpy(&(newstate[curpos]), &tmpstate, 1);
        curpos++;
        /* event 1 -> 5 */
        tmpstate.state = 3;
        memcpy(&(newstate[curpos]), &tmpstate, 1);
        curpos++;
        break;
      default:
        break;
      }
    }
    newstate[0] = curpos-1;
    if (newstate[0] == 0)
      return 1; /* TESLA_ERROR */
    memcpy(MAIN_PTR(tip), &newstate, sizeof(newstate));
    return 0;

  default:
    return 1; /* TESLA_UNKNOWN_EVENT */
  }
}

