/*
 * This file is autogenerated by the Tesla CFA compiler
 * via: ../../cfa/splc -t tesla -s ssh ssh.spl
 */

#ifndef SSH_DEFS_H
#define SSH_DEFS_H

#include <sys/types.h>

/*
 * Names for events that will trigger SSH rules
 */
#define SSH_EVENT_FUNC_PROLOGUE_PACKET_SEND 0
#define SSH_EVENT_FUNC_PROLOGUE_PACKET_START 1
#define SSH_EVENT_FUNC_PROLOGUE_PACKET_SET_CONNECTION 2

/*
 * Prod the SSH state machine, return (1) if the assertion failed
 */
struct tesla_instance;
void ssh_automata_init(struct tesla_instance *);
int ssh_automata_prod(struct tesla_instance *tip, u_int event);

/*
 * "Public" interfaces to the assertion, to be invoked by load, unload
 * and instrumentation handlers.
 */
#ifndef _KERNEL
void	ssh_init(int scope);
void	ssh_destroy(void);
void    ssh_setaction_debug(void);
#endif
#endif /* SSH_DEFS_H */
