#!/bin/sh

LINE="======================================================================"

CFLAGS="$*"
export CFLAGS

echo $LINE
echo "Compiling demo with CFLAGS '$CFLAGS'..."
echo $LINE
make clean all || exit 1
echo $LINE
echo

echo $LINE
echo "Running demo..."
echo $LINE
./audit-demo
echo $LINE
