#!/bin/sh
#
# Invoke this script with a maximum number of assertions:
#   ./run-to 3
#
# and, optionally, some environment variables:
#   TRIALS=5 CFLAGS="-fno-omit-frame-pointer" ./run-to 3
#
# RUN: %s 3 > %t.out 2>&1
# RUN: FileCheck -input-file %t.out %s
#

cd `dirname $0`

declare -i MAX=$1
if [ "$MAX" == "" ]; then
	echo "Usage: run-to <runs> [CFLAGS]"
	exit 1
fi

if [ "$TRIALS" == "" ]; then
	 declare -i TRIALS=3
fi

declare -i TRIALS=${TRIALS}

export LD_LIBRARY_PATH=$TESLA_BUILD_DIR/libtesla/src


echo "#"
echo "# TESLA context-entry-and-exit microbenchmark"
echo "#"
echo

function run {
	RUNS=$1
	FLAGS="${CFLAGS} $2 -D RUNS=${RUNS}"

	echo "# CFLAGS = '${FLAGS}'"
	echo "# asserts\truns\c"

	for t in `seq ${TRIALS}`; do echo "\ttrial$t\c"; done
	echo

	declare -i i=0
	while [ ${MAX} -gt $i ]; do
		CFLAGS="${FLAGS} -D TESLA=$i" make --quiet clean all || exit 1

		echo "  $i\t\t${RUNS}\c"

		for t in `seq ${TRIALS}`; do
			echo "\t\c"
			./instrcost
		done
		echo

		i=i+1
	done

	echo
}

run 100000 "-D DO_WORK"
run 1000000 ""

#
# CHECK: asserts runs trial1 trial2 trial3
# CHECK-NEXT: 0
# CHECK-NEXT: 1
# CHECK-NEXT: 2
#
