#!/usr/bin/env bash
#
# Invoke this script with a maximum number of assertions:
#   ./run-to 3
#
# and, optionally, some environment variables:
#   TRIALS=5 CFLAGS="-fno-omit-frame-pointer" ./run-to 3
#
# RUN: %s 3 > %t.out 2>&1
# RUN: FileCheck -input-file %t.out %s
#

cd `dirname $0`

MAX=$1
if [ "$MAX" == "" ]; then
	echo "Usage: run-to <runs> [CFLAGS]"
	exit 1
fi

if [ "$TRIALS" == "" ]; then
	 TRIALS=3
fi

TRIALS=${TRIALS}

export LD_LIBRARY_PATH=$TESLA_BUILD_DIR/libtesla/src


echo "#"
echo "# TESLA context-entry-and-exit microbenchmark"
echo "#"
echo

function run {
	RUNS=$1
	FLAGS="${CFLAGS} $2 -D RUNS=${RUNS}"

	echo "# CFLAGS = '${FLAGS}'"
	echo -en "# asserts\truns"

	for t in `seq ${TRIALS}`; do echo -en "\ttrial$t"; done
	echo

	i=0
	for i in `seq ${MAX}`; do
		CFLAGS="${FLAGS} -D TESLA=$i" make clean all || exit 1

		echo -en "  $i\t\t${RUNS}"

		for t in `seq ${TRIALS}`; do
			echo -en "\t"
			./instrcost
		done
		echo

		i=i+1
	done

	echo
}

run 100000 "-D DO_WORK"
run 1000000 ""

#
# CHECK: asserts runs trial1 trial2 trial3
# CHECK-NEXT: 0
# CHECK-NEXT: 1
# CHECK-NEXT: 2
#
