#!/bin/sh

#
# This script provides a wrapper around make that sets some important
# variables based on a couple of inputs:
#
# PATH                          should include the LLVM/Clang you want to use
#                               and (optionally) the 'tesla' script
#
# TESLA            [optional]   if the 'tesla' script isn't on the PATH,
#                               this variable should point to it
#
# TESLA_BUILD_DIR  [optional]   if TELSA hasn't been installed to the PATH,
#                               this is where its build outputs can be found
#                               (used by 'tesla' script)
#


# Find the various tools we need.
XCC=`which clang`
XCXX=`which clang++`
XCPP=clang-cpp
XLLC=`which llc`
BINUTILS=$(dirname `which ar`)


# Find the TESLA driver script (if not already set).
if [ "$TESLA" == "" ]; then
	TESLA=`which tesla`
fi

if [ "$TESLA" == "" ]; then
	echo "Unable to find 'tesla' script; set PATH or TESLA variable"
	exit 1
fi


# Run make, setting some variable and passing command-line arguments through.
make \
	XCC=$XCC XCXX=$XCXX XCPP=$XCPP XLLC=$XLLC TESLA=$TESLA \
	CROSS_BINUTILS_PREFIX=$BINUTILS \
	CONFIGARGS=-t -DNO_MODULES -DWITHOUT_FORMAT_EXTENSIONS \
	$*

