#!/bin/sh

usage() {
	echo "Usage:  tesla <tool> [tool arguments]"
	echo
	echo "  where <tool> is one of:"
	echo "    - analyse       (analyse C assertions, produce TESLA IR)"
	echo "    - graph         (convert TESLA IR into GraphViz .dot format)"
	echo "    - instrument    (add TESLA instrumention to LLVM IR)"
	echo "    - read          (read information from TESLA IR)"
	echo
}

if [ "$1" == "" ]; then
	usage
	exit 1
fi

if [ "$TESLA_BUILD_DIR" != "" ]; then
  if [ ! -d "$TESLA_BUILD_DIR/tesla/analyser" ]; then
    echo "No 'tesla/analyser' directory in \$TESLA_BUILD_DIR: $TESLA_BUILD_DIR"
    exit 1
  fi

  export PATH="$TESLA_BUILD_DIR/tesla/analyser:$TESLA_BUILD_DIR/tesla/instrumenter:$TESLA_BUILD_DIR/tesla/tools/graph:$TESLA_BUILD_DIR/tesla/tools/read:$PATH"
else
  export PATH="$(dirname $0):$PATH"
fi

tesla-$*

