#!/bin/sh

usage() {
	echo "Usage:  tesla <tool> [tool arguments]"
	echo
	echo "  where <tool> is one of:"
	echo "    - analyse       (analyse C assertions, produce TESLA IR)"
	echo "    - cat           (combine several TESLA IR files)"
	echo "    - get-triple    (get the host's LLVM triple)"
	echo "    - graph         (convert TESLA IR into GraphViz .dot format)"
	echo "    - instrument    (add TESLA instrumention to LLVM IR)"
	echo "    - read          (read information from TESLA IR)"
	echo
}

if [ ! $1 ]; then
	usage
	exit 1
fi

TOOL_NAME="tesla-$1"
shift

#
# TESLA_BUILD_DIR takes precedence, otherwise try to find beside wrapper
#
if [ $TESLA_BUILD_DIR ]; then
	TOOL=`find $TESLA_BUILD_DIR/tesla -name $TOOL_NAME`
	if [ ! "$TOOL" ]; then
		echo "No '$TOOL_NAME' in TESLA_BUILD_DIR ('$TESLA_BUILD_DIR')."
		exit 1
	fi
else
	TOOL="$(dirname $(which $0))/${TOOL_NAME}"
	echo $TOOL
	if [ ! -e "${TOOL}" ]; then
		TOOL=
	fi
fi

#
# Last ditch effort to find in PATH
#
if [ -z "$TOOL" ]; then
	TOOL=`which $TOOL_NAME`
	if [ ! "$TOOL" ]; then
		echo "No '$TOOL_NAME' in \$PATH; try setting TESLA_BUILD_DIR?"
		exit 1
	fi
fi

$TOOL "$@"
if [ $? != 0 ] ; then
	echo Invocation was $TOOL "$@"
fi

