/*
 * This file is autogenerated by the Tesla CFA compiler
 * via: ../../cfa/splc -t tesla -s tcpc tcpc.spl
 */

#ifndef TCPC_DEFS_H
#define TCPC_DEFS_H

#include <sys/types.h>

/*
 * Names for events that will trigger TCPC rules
 */
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_LAST_ACK 0
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_CLOSING 1
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_CLOSED 2
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_ESTABLISHED 3
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_FIN_WAIT_1 4
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_FIN_WAIT_2 5
#define TCPC_EVENT_FUNC_PROLOGUE_TCP_FREE 6
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_SYN_SENT 7
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_CLOSE_WAIT 8
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_SYN_RECEIVED 9
#define TCPC_EVENT_TP_T_STATE_ASSIGN_TCPS_TIME_WAIT 10

/*
 * Prod the TCPC state machine, return (1) if the assertion failed
 */
struct tesla_instance;
void tcpc_automata_init(struct tesla_instance *);
int tcpc_automata_prod(struct tesla_instance *tip, u_int event);

/*
 * "Public" interfaces to the assertion, to be invoked by load, unload
 * and instrumentation handlers.
 */
void	tcpc_init(int scope);
void	tcpc_destroy(void);
void    tcpc_setaction_debug(void);
#endif /* TCPC_DEFS_H */
