function,tcp_free
field_assign,tp,t_state,TCPS_CLOSED
field_assign,tp,t_state,TCPS_LAST_ACK
field_assign,tp,t_state,TCPS_CLOSE_WAIT
field_assign,tp,t_state,TCPS_ESTABLISHED
field_assign,tp,t_state,TCPS_CLOSED
field_assign,tp,t_state,TCPS_TIME_WAIT
field_assign,tp,t_state,TCPS_FIN_WAIT_2
field_assign,tp,t_state,TCPS_TIME_WAIT
field_assign,tp,t_state,TCPS_CLOSING
field_assign,tp,t_state,TCPS_FIN_WAIT_1
field_assign,tp,t_state,TCPS_SYN_RECEIVED
field_assign,tp,t_state,TCPS_SYN_SENT
field_assign,tp,t_state,TCPS_CLOSED
