/*
 * This file is autogenerated by the Tesla CFA compiler
 * via: ../../cfa/splc -t tesla -s tcpc tcpc.spl
 */

#ifndef TCPC_DEFS_H
#define TCPC_DEFS_H

#include <sys/types.h>

/*
 * Names for events that will trigger TCPC rules
 */
#define TCPC_EVENT_CLOSING 0
#define TCPC_EVENT_FIN_WAIT_1 1
#define TCPC_EVENT_FIN_WAIT_2 2
#define TCPC_EVENT_SYN_SENT 3
#define TCPC_EVENT_CLOSED 4
#define TCPC_EVENT_CLOSE_WAIT 5
#define TCPC_EVENT_ESTABLISHED 6
#define TCPC_EVENT_LAST_ACK 7
#define TCPC_EVENT_TIME_WAIT 8
#define TCPC_EVENT_SYN_RCVD 9

/*
 * Prod the TCPC state machine, return (1) if the assertion failed
 */
struct tesla_instance;
int tcpc_automata_prod(struct tesla_instance *tip, u_int event);

/*
 * "Public" interfaces to the assertion, to be invoked by load, unload
 * and instrumentation handlers.
 */
void	tcpc_init(int scope);
void	tcpc_destroy(void);
#endif /* TCPC_DEFS_H */
